language: java

jdk:
  - oraclejdk8

sudo: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

dist: trusty

branches:
  only:
    - metric_tests

before_install:
  - sudo apt-get update
  - sudo apt-get install python3

script:
  - ./gradlew build --scan -s
  - export PATH = "$PATH"
  - chmod a+rwx coverage.py
  - python3 coverage.py